export const getLanguage = (marketplace) => {
  const marketplaceMap = {
    PT: "en-GB",
    GB: "en-GB",
    ZA: "en-GB",
    CZ: "en-GB",
    PH: "en-GB",
    SK: "en-GB",
    SI: "en-GB",
    SG: "en-GB",
    SE: "en-GB",
    CH: "en-GB",
    SA: "en-GB",
    LU: "en-GB",
    FI: "en-GB",
    IN: "en-GB",
    IL: "en-GB",
    CA: "en-GB",
    IE: "en-GB",
    ID: "en-GB",
    RO: "en-GB",
    HR: "en-GB",
    BG: "en-GB",
    NZ: "en-GB",
    BE: "en-GB",
    NO: "en-GB",
    NL: "en-GB",
    AU: "en-GB",
    AT: "en-GB",
    MY: "en-GB",
    DK: "en-GB",
    AE: "en-GB",
    PL: "pl",
    FR: "fr",
    IT: "it",
    US: "en",
    JP: "ja",
    ES: "es-ES",
    HU: "hu",
    KR: "ko",
    TW: "zh-Hant",
    TR: "tr",
    TH: "th",
    GR: "el",
    MX: "es-419",
    DE: "de",
  };

  return marketplaceMap[marketplace];
};
